version: '3'

services:
  app:
    build: .
    # verificar se o db tรก rodando e executar o entrypoint
    # importante: chmod +x .docker/entrypoint.sh
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on: 
      - db
    # extra_hosts: 
    #   - "host.docker.internal:172.17.0.1"

  db:
    build: ./.docker/mysql
    restart: always
    # habilita o terminal caso precise
    tty: true
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=fin
      - MYSQL_ROOT_PASSWORD=root